### ISSUE TITLE
postMessage and onMessage not work on Chrome 70

### ISSUE THREAD

**Issue by LyCharlie** [scazzy/react-native-webview-autoheight#19]
It works fine before I upgrade my Chrome, but when I upgrade my Chrome to 70 postMessage not work and onMessage not call ,so I can not get content height , what should I do?

**Comment by jollyBaker** [comment]
same problem, no solution found yet to get an autoheight webview depending on the content

**Comment by mstadius** [comment]
Copying the code from [this post](https://github.com/react-native-community/react-native-webview/issues/29#issuecomment-430779411) to the start of `injectedScript` in the components index.js file fixed the problem for me on Android. I have not yet tested what happens on iOS. So the modified function looks like this:

```js
const injectedScript = function() {
  // Modification start
  const originalPostMessage = window.postMessage;
  const patchedPostMessage = function (message, targetOrigin, transfer) {
    originalPostMessage(message, targetOrigin, transfer);
  };
  patchedPostMessage.toString = function () {
    return String(Object.hasOwnProperty).replace('hasOwnProperty', 'postMessage');
  };
  window.postMessage = patchedPostMessage;
  // Modification end

  function waitForBridge() {
    if (window.postMessage.length !== 1){
      setTimeout(waitForBridge, 200);
    }
    else {
      let height = 0;
      if(document.documentElement.clientHeight>document.body.clientHeight)
      {
        height = document.documentElement.clientHeight
      }
      else
      {
        height = document.body.clientHeight
      }
      postMessage(height)
    }
  }
  waitForBridge();
};
```

**Comment by jollyBaker** [comment]
This fixes the problem on Android, but will nothing show on iOS.

Workaround for now having two webviews with and without the fix and show depending on the OS the corresponding webview

**Comment by jollyBaker** [comment]
version 1.0.6 fixes this issue

**Comment by LyCharlie** [comment]
it works thank you
