### ISSUE TITLE
[Android] Don't work

### ISSUE THREAD

**Issue by bltnico** [scazzy/react-native-webview-autoheight#4]
Same as the issue https://github.com/scazzy/react-native-webview-autoheight/issues/2, when I use  `startInLoadingState` loader doesn't disappear !

RN : 0.39.0
react-native-webview-autoheight : 1.0.2 & 1.0.4
Android : 7.1 (emulator)

**Comment by duongtranpyco** [comment]
@scazzy any updates?

**Comment by dashracer** [comment]
Check this [PR](https://github.com/scazzy/react-native-webview-autoheight/pull/20
)

**Comment by scazzy** [comment]
@dashracer  thanks for the PR. have merged and published on npm.
Do perform a test of all cases. I haven't got time to test it out.

@bltnico @duongtranpyco
