### ISSUE TITLE
Can't call .stopLoading() for opening links on HTML Page

### ISSUE THREAD

**Issue by achauhancn** [scazzy/react-native-webview-autoheight#6]
I want to open links externally, 
so I was using 
```
ref={(ref) => { this.webview = ref; }}
onNavigationStateChange={(event) => {
    this.webview.stopLoading();
    Linking.openURL(event.url);
}}
```

But .stopLoading() doesn't work, since real WebView component is nested in this one.
Can someone suggest something, so that I can open links externally?

**Comment by ckeeney** [comment]
@achauhancn did you ever resolve this?  I'm having this same problem right now.

**Comment by achauhancn** [comment]
Yes I edited the code and added stopLoading() function
In render() method add ref for Webview

```
<WebView
        ref={(ref) => { this.webview = ref; }} . // ADD THIS LINE
        injectedJavaScript={'(' + String(injectedScript) + ')();'}
        scrollEnabled={this.props.scrollEnabled || false}
        onMessage={this._onMessage}
        javaScriptEnabled={true}
        automaticallyAdjustContentInsets={true}
        {...this.props}
        style={[{width: _w}, this.props.style, {height: _h}]}
      />
```
And finally add stopLoading() function in MyWebView
```
stopLoading() {
    this.webview.stopLoading();
}
```

**Comment by ckeeney** [comment]
Thanks.  I figured editing the library to add a ref was the most obvious way.

**Comment by scazzy** [comment]
@achauhancn could you send a PR for the fix?
